### ISSUE TITLE
avsc files compiled in random order

### ISSUE THREAD

**Issue by ch4mpy** [sbt/sbt-avro#13]
The order in which avsc files are compiled depends on the underlying file system (i.e. under OSX its is alphabetical, under some linux distros  it's not).
This is an issue when you have a record type that is used in different other types.
I propose a hack to sort avsc files before compilation on a fork of this project. Feel free to pick / adapt what you think makes sense at https://github.com/ch4mpy/sbt-avro

**Comment by andreionut** [comment]
Looks like @cavorite is looking for a maintainer. Would you be interested in taking over?

**Comment by andreionut** [comment]
@cavorite I would like to take over this project. We started using Avro extensively and your plugin is an integral part of our build process.
I don't know how to do this, but I already forked @ch4mpy 's repo and will try to publish it to Bintray
Let me know what you think.

**Comment by markon** [comment]
+1. 
Thanks a lot for this patch!

**Comment by themodernlife** [comment]
In the interest of helping folks get here from Google... anyone encountering this in the future, the error you will see is something like

```
[error] (foobar/avro:generate) org.apache.avro.SchemaParseException: "com.example.MetaInfo" is not a defined name. The type of the "MetaInfo" field must be a defined name or a {"type": ...} expression.
[error] Total time: 0 s, completed Jul 8, 2016 12:42:10 PM
```

You might be able to work around this by prefixing the `avsc` schema file for any types you are going to reuse in subsequent `avsc` files by `0` or something.  For example, we wanted to share a type, `MetaInfo` so we just named the file `0metainfo` and things worked ok.

The reason this works is because the parser remembers all previously encountered names and the same parser is used for each subsequent file.

From `SbtAvro.scala`:

```
val schemaParser = new Schema.Parser();  // <-- reused for each file
...
for (schema <- (srcDir ** "*.avsc").get) {
  log.info("Compiling Avro schema %s".format(schema))
  val schemaAvr = schemaParser.parse(schema.asFile)
  val compiler = new SpecificCompiler(schemaAvr)
  compiler.setStringType(stringType)
  compiler.compileToDestination(null, target)
}
```

**Comment by andreionut** [comment]
@themodernlife Try this fork: https://github.com/andreionut/sbt-avro, it fixes the dependency issue.

**Comment by julianpeeters** [comment]
I ran into the same error when using relative type names, the same in @andreionut 's fork as well. Is this the proper place to submit a fix? https://github.com/sbt/sbt-avro/pull/28

thx

**Comment by dollschasingmen** [comment]
+1 this causes issues for us as well

**Comment by benmccann** [comment]
@julianpeeters sent a PR for this a month ago. Thanks! I'm waiting for him to address some comments before I merge it. Others are welcome to submit PRs as well if this is something you really need

**Comment by gigaSproule** [comment]
Has PR #28 stalled?

**Comment by xuanli09** [comment]
Is it possible to amend PR #28 and merge it in? I don't think the submitter is alive anymore :(
