### ISSUE TITLE
Support for older avro versions (i.e. < 1.8.2)

### ISSUE THREAD

**Issue by kevinarchambeau** [sbt/sbt-avro#134]
Are Avro versions older than 1.8.2 supposed to be supported?

 I ask because it seems that `compiler.setEnableDecimalLogicalType(enableDecimalLogicalType)` is being set without checking the Avro compiler version and this seems to have been introduced in 1.8.2.

Example:
project sets:
```
addSbtPlugin("com.github.sbt" % "sbt-avro" % "3.4.2")

libraryDependencies += "org.apache.avro" % "avro-compiler" % "1.8.0"
```

on `sbt compile` you can see the error: `(Compile / avroGenerate) java.lang.NoSuchMethodError: org.apache.avro.compiler.specific.SpecificCompiler.setEnableDecimalLogicalType(Z)V`

**Comment by RustedBones** [comment]
Your are right. In the `1.8` test folder we only test with
```sbt
libraryDependencies += "org.apache.avro" % "avro-compiler" % "1.8.2" 
```
As avro 1.8 is not maintained anymore, I don't think we'll add support version older than `1.8.2`

**Comment by kevinarchambeau** [comment]
Ok, thanks for the confirmation :)
