### ISSUE TITLE
maintainer

### ISSUE THREAD

**Issue by orphean-zz** [sbt/sbt-avro#15]
Hello,

We use your plugin sbt-avro internally in our build. I've made a few changes and rather than forking, I would like to maintain this. let me know.

**Comment by cavorite** [comment]
Hi,

Thanks for the interest. I'll add you as a contributor and also I'll transfer the repository to the sbt organization so that it can be easily managed by the community.

**Comment by cavorite** [comment]
The project is now part of the sbt organization and you should be able to contribute. I'll update the links from my website, but we should be able to start using GitHub pages for all the documentation.

Thanks for taking over the project.

**Comment by orphean-zz** [comment]
many thanks! I will start post Easter

**Comment by benmccann** [comment]
My comment shows me as "sbt member", but that doesn't seem to give me permission to merge PRs, close issues, etc. Are you able to add the whole SBT group to the project?

**Comment by cavorite** [comment]
@benmccann I added you to the project. Let me know if you're interested in being a maintainer and I'll add you to the admins as well.
