### ISSUE TITLE
Latest version not available in repo

### ISSUE THREAD

**Issue by eli-jordan** [sbt/sbt-avro#16]
The latest version available in the repo is 0.3.2 not 1.0.1 as mentioned in the readme

http://dl.bintray.com/sbt/sbt-plugin-releases/com.cavorite/sbt-avro/scala_2.10/sbt_0.13

**Comment by orphean-zz** [comment]
Hi,

Fixed. You are correct, the wrong version is in the README, if you try and download it. However, if you check under project/Build.scala, the version is 1.0.1. Guess it has just not been published with that version.

**Comment by eli-jordan** [comment]
Yep I noticed the version in Build.scala. Perhaps the latest version should be published?
