### ISSUE TITLE
referring to "compile" in build.sbt causes build error

### ISSUE THREAD

**Issue by ScalaWilliamTeralytics** [sbt/sbt-avro#18]
e.g.

```
build.sbt:60: error: reference to compile is ambiguous;
it is imported twice in the same scope by
import _root_.sbtavro.SbtAvro._
and import Keys._
    compile in Test := Def.taskDyn {
    ^
sbt.compiler.EvalException: Type error in expression
[error] sbt.compiler.EvalException: Type error in expression
```

Probably because of this https://github.com/sbt/sbt-avro/blob/375e27792d2ba2047979b6ce1068124933326e61/src/main/scala/sbtavro/SbtAvro.scala#L49

so the compiler probably 'sees' this private field when it shouldn't

**Comment by benmccann** [comment]
I just merged https://github.com/sbt/sbt-avro/pull/20, so hopefully this is fixed now
