### ISSUE TITLE
Setting 'avroSource' apparently ignored

### ISSUE THREAD

**Issue by epalace** [sbt/sbt-avro#42]
The following configuration ignores `avroSource`, but not the other settings.

```scala
lazy val model = project
  .in(file("model"))
  .enablePlugins(SbtAvro)
  .settings(
    avroSource := (baseDirectory.value.getAbsoluteFile / "my_dir"),
    avroStringType := "CharSequence",
    avroFieldVisibility := "private",
    avroOptionalGetters := true,
    name := s"${baseName}-model",
    libraryDependencies ++= Libraries.model
  )
```

Am I doing something wrong here? I see `avroSource` is initialized in a different part than the rest of settings, and probably always overriden by the default `sourceDirectory.value / "avro"`

**Comment by alejandroarevalo** [comment]
@epalace I solved it by specifying the property for the Compile configuration
  `avroSource in Compile := (baseDirectory.value.getAbsoluteFile / "my_dir")`

**Comment by epalace** [comment]
Thank you @alejandroarevalo 👍

**Comment by blackavec** [comment]
love you @alejandroarevalo, i've been dealing with this since yesterday and i just fixed it by your comment.
thanks alot 👍
