### ISSUE TITLE
How to downgrade version of Avro

### ISSUE THREAD

**Issue by antonoal** [sbt/sbt-avro#48]
Hi,

Is there a way I can use this plugin with avro v 1.8.0 instead of 1.8.2? The reason being this open bug: https://issues.apache.org/jira/browse/AVRO-1924 that causes compilation errors in my codebase.

Thanks in advance

Alex

**Comment by nevillelyh** [comment]
Does `(version in AvroConfig) := "1.8.0"` work for you?

**Comment by antonoal** [comment]
Apologies for not closing this one back in Feb. 
I solved it by adding dependencyOverrides to plugins.sbt. Any attempt to override the version after sbt loaded the plugin (and it's dependency avro v1.8.2) was pointless as sbt would have already loaded avro.
