### ISSUE TITLE
MalformedInputException when running in sbt cloud-builder docker container

### ISSUE THREAD

**Issue by alde** [sbt/sbt-avro#50]
Hi

When running inside the sbt cloud-builder docker container, I get the following exception:

`java.io.UncheckedIOException: java.nio.charset.MalformedInputException: Input length = 1`

I believe this is because it hasn't got file.encoding="UTF-8", and no encoding is specified when reading the source file, making scala use the default encoding of the system.

I built a local version of this library, and the following patch fixes the issue:

```diff
diff --git a/src/main/scala/sbtavro/SbtAvro.scala b/src/main/scala/sbtavro/SbtAvro.scala
index b5406a0..ccc3735 100644
--- a/src/main/scala/sbtavro/SbtAvro.scala
+++ b/src/main/scala/sbtavro/SbtAvro.scala
@@ -163,7 +163,7 @@ object SbtAvro extends AutoPlugin {
   }

   def fileText(f: File): String = {
-    val src = Source.fromFile(f)
+    val src = Source.fromFile(f, "UTF-8")
     try {
       return src.getLines.mkString
     } finally {
```

I think being explicit about the encoding when reading the file makes sense, and setting it to UTF-8 should be safe.

**Comment by nevillelyh** [comment]
Hey this seems like a useful fix. Do you want to submit a PR?

**Comment by alde** [comment]
Absolutely, I can do that.
