### ISSUE TITLE
1.1.4 Release with the dependency sorting fixes from #52

### ISSUE THREAD

**Issue by patrickwmcgee** [sbt/sbt-avro#54]
@benmccann I was wondering when a release with the changes from #52 that should fix dependency sorting issues will be made?

**Comment by benmccann** [comment]
I'm no longer maintaining any SBT plugins. I only merged the change since I had reviewed it already quite awhile ago. I suggest you find another SBT maintainer to take over cutting a release

**Comment by patrickwmcgee** [comment]
Thank you for the update!

**Comment by nevillelyh** [comment]
We'd (Spotify) like to help since we're heavy users of this plugin. Is there something we can work out with the sbt maintainers? cc @eed3si9n

**Comment by eed3si9n** [comment]
@nevillelyh 

> We'd (Spotify) like to help since we're heavy users of this plugin. Is there something we can work out with the sbt maintainers?

Nice. I just read this. Let me know who's going to maintain the plugin, and I'd be happy to add them to the team.

**Comment by nevillelyh** [comment]
Please add me then. Thanks. Guess that'll give me merge rights yeah? How do I go about releasing?

**Comment by eed3si9n** [comment]
@nevillelyh I just invited you to Bintray sbt organization, which gives you the right to publish to https://bintray.com/sbt/sbt-plugin-releases/sbt-avro-1.8

**Comment by nevillelyh** [comment]
Just released 1.1.4
