### ISSUE TITLE
No processor claimed any of these annotations: org.apache.avro.specific.AvroGenerated

### ISSUE THREAD

**Issue by TrixiaBelleza** [sbt/sbt-avro#61]
So the .avsc file I made has succesfully generated to an Avro Class. However, on sbt compile, I'm getting this error.
[warn] No processor claimed any of these annotations: org.apache.avro.specific.AvroGenerated
[error] warnings found and -Werror specified

I can't proceed unless I suppress or fix this warning.

**Comment by RustedBones** [comment]
Are your avro versions in sync between project and compiler ?
the version used in tour `project/plugins.sbt` and in the `build.sbt`

**Comment by RustedBones** [comment]
@TrixiaBelleza where are you now with this issue ?
Since there was no follow-up, I will close it but feel free to re-open if you're still experiencing the problem.
