### ISSUE TITLE
`avroOptionalGetters` not available

### ISSUE THREAD

**Issue by ffossum** [sbt/sbt-avro#86]
Hi,
I wanted to use the `avroOptionalGetters` setting in my project, but sbt complained that it could not find it.
After checking this repo I see there hasn't been a release since the `avroOptionalGetters` feature was added.

Can you please release `3.2` which includes this feature? Thank you!

**Comment by RustedBones** [comment]
Indeed, the tag has been pushed from #46 but there are no artifact released.
@nevillelyh do you remember the status on this ? Seems that the tag needs to be deleted and publishing to be retried.

**Comment by RustedBones** [comment]
The version is released. Be mindful of the org migration :)
